# Generated by Django 4.2.7 on 2023-11-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description_short', models.TextField()),
                ('description_long', models.TextField()),
                ('lat', models.FloatField(verbose_name='широта')),
                ('lng', models.FloatField(verbose_name='долгота')),
            ],
        ),
    ]
