# Generated by Django 4.2.7 on 2023-11-26 03:44

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_image_options_alter_image_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='description_long',
            field=tinymce.models.HTMLField(),
        ),
    ]
