# Generated by Django 4.2.7 on 2023-12-19 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_alter_image_location_alter_image_photo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='description_long',
            new_name='long_description',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='description_short',
            new_name='short_description',
        ),
    ]
